
<?php if ($this->error == 1) { ?>
	<div class="alert alert-error">Gebruikersnaam/wachtwoord verkeerd!</div>
<?php } else { ?>
	<div class="alert">Eerst even inloggen!</div>
<?php } ?>

<!--
<form action="/" method="post">
	
	<input type="text" name="username" value="" placeholder="Studentnummer..." />
	
	<input type="password" name="password" value="" placeholder="Wachtwoord..." />
	
	<input type="submit" name="" value="Inloggen" class="btn btn-primary" />
	
	
</form> -->
