<!DOCTYPE html>
<html lang="nl">
  <head>
    <meta charset="utf-8">
    <title>Justitia uitbreiding</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <script src="/js/jquery.min.js"></script>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Justitia Uitbreiding</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="/import">1. Importeren</a></li>
              <li><a href="/grade">2. Becijferen</a></li>
              <li><a href="/fraud">3. Fraude</a></li>
              <li><a href="/export">4. Exporteren</a></li>
             <!-- <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
             </li> -->
            
            <?php $session = new Zend_Session_Namespace('session'); ?>
            
            <?php if (isset($session->cookiejar)) { ?>
            	<li><a href="/logout">Uitloggen</a></li>
            	</ul>
            <?php } else { ?>
            	</ul>
            <form class="navbar-form pull-right" method="post" action="/">
              <input class="span2" type="text" name="username" placeholder="Gebruikersnaam">
              <input class="span2" type="password" name="password" placeholder="Wachtwoord">
              <button type="submit" class="btn">Inloggen</button>
            </form>
            <?php } ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
    	
    	<?php echo $this->layout()->content; ?>

      

      <hr>

      <footer>
        <p>&copy; Kiezo 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="/js/bootstrap.min.js"></script>


  </body>
</html>